// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Desafio Técnico - João Pedro Podlasnisky
//
//  Essa API foi desenvolvida para atender os requisitos solicitados no desafio prático da UBOTs.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1
//  Version: 1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
