// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Essa API foi desenvolvida para atender os requisitos solicitados no desafio prático da UBOTs.",
    "title": "Desafio Técnico - João Pedro Podlasnisky",
    "version": "1.0"
  },
  "basePath": "/v1",
  "paths": {
    "/clienteMaiorCompraUnica": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cliente"
        ],
        "summary": "Retorna o cliente com maior valor gasto em uma única compra",
        "operationId": "clienteMaiorCompraUnica",
        "responses": {
          "200": {
            "description": "Cliente com maior compra única",
            "schema": {
              "$ref": "#/definitions/Cliente"
            }
          },
          "500": {
            "description": "Status 500",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    },
    "/clientesGastoTotal": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cliente"
        ],
        "summary": "Retorna os clientes ordenados de forma decrescente com base no total de compras realizado",
        "operationId": "clientesGastoTotal",
        "responses": {
          "200": {
            "description": "Clientes ordenados pelo total de compras",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Cliente"
              }
            }
          },
          "500": {
            "description": "Status 500",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    },
    "/clientesMaisFieis/{tamanhoLista}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cliente"
        ],
        "summary": "Retorna os clientes com maior número de compras",
        "operationId": "clientesMaisFieis",
        "parameters": [
          {
            "type": "integer",
            "name": "tamanhoLista",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Cliente com maior compra única",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Cliente"
              }
            }
          },
          "500": {
            "description": "Status 500",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    },
    "/recomendacaoVinho/{cpfCliente}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "vinho"
        ],
        "summary": "Recomenda um vinho com base no histórico de compras de um determinado cliente",
        "operationId": "recomendacaoVinho",
        "parameters": [
          {
            "type": "string",
            "name": "cpfCliente",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Vinho recomendado",
            "schema": {
              "$ref": "#/definitions/VinhoRecomendado"
            }
          },
          "500": {
            "description": "Status 500",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Cliente": {
      "description": "Dados do cliente",
      "type": "object",
      "properties": {
        "cpf": {
          "description": "CPF do Cliente",
          "type": "string",
          "minLength": 1
        },
        "maiorCompraUnicaDoCliente": {
          "description": "Maior compra única do cliente",
          "type": "number"
        },
        "nomeCliente": {
          "description": "Nome do Cliente",
          "type": "string",
          "minLength": 1
        },
        "quantidadeDeComprasDoCliente": {
          "description": "Quantidade de compras realizadas (fidelidade do cliente)",
          "type": "integer"
        },
        "totalEmComprasDoCliente": {
          "description": "Total em compras realizadas pelo cliente",
          "type": "number"
        }
      }
    },
    "Erro": {
      "type": "object",
      "properties": {
        "Mensagem": {
          "type": "string"
        }
      }
    },
    "Token": {
      "type": "string",
      "minLength": 1
    },
    "VinhoRecomendado": {
      "description": "Recomendação de vinho para um cliente determinado",
      "type": "object",
      "properties": {
        "categoria": {
          "description": "Categoria do Vinho",
          "type": "string",
          "minLength": 1
        },
        "pais": {
          "description": "País de origem do vinho",
          "type": "string",
          "minLength": 1
        },
        "preco": {
          "description": "Preço do Vinho",
          "type": "number"
        },
        "produto": {
          "description": "Nome do Produto",
          "type": "string",
          "minLength": 1
        },
        "safra": {
          "description": "Ano da Safra do Vinho",
          "type": "integer"
        },
        "variedade": {
          "description": "Variedade do Vinho",
          "type": "string",
          "minLength": 1
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Essa API foi desenvolvida para atender os requisitos solicitados no desafio prático da UBOTs.",
    "title": "Desafio Técnico - João Pedro Podlasnisky",
    "version": "1.0"
  },
  "basePath": "/v1",
  "paths": {
    "/clienteMaiorCompraUnica": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cliente"
        ],
        "summary": "Retorna o cliente com maior valor gasto em uma única compra",
        "operationId": "clienteMaiorCompraUnica",
        "responses": {
          "200": {
            "description": "Cliente com maior compra única",
            "schema": {
              "$ref": "#/definitions/Cliente"
            }
          },
          "500": {
            "description": "Status 500",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    },
    "/clientesGastoTotal": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cliente"
        ],
        "summary": "Retorna os clientes ordenados de forma decrescente com base no total de compras realizado",
        "operationId": "clientesGastoTotal",
        "responses": {
          "200": {
            "description": "Clientes ordenados pelo total de compras",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Cliente"
              }
            }
          },
          "500": {
            "description": "Status 500",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    },
    "/clientesMaisFieis/{tamanhoLista}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cliente"
        ],
        "summary": "Retorna os clientes com maior número de compras",
        "operationId": "clientesMaisFieis",
        "parameters": [
          {
            "type": "integer",
            "name": "tamanhoLista",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Cliente com maior compra única",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Cliente"
              }
            }
          },
          "500": {
            "description": "Status 500",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    },
    "/recomendacaoVinho/{cpfCliente}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "vinho"
        ],
        "summary": "Recomenda um vinho com base no histórico de compras de um determinado cliente",
        "operationId": "recomendacaoVinho",
        "parameters": [
          {
            "type": "string",
            "name": "cpfCliente",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Vinho recomendado",
            "schema": {
              "$ref": "#/definitions/VinhoRecomendado"
            }
          },
          "500": {
            "description": "Status 500",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Cliente": {
      "description": "Dados do cliente",
      "type": "object",
      "properties": {
        "cpf": {
          "description": "CPF do Cliente",
          "type": "string",
          "minLength": 1
        },
        "maiorCompraUnicaDoCliente": {
          "description": "Maior compra única do cliente",
          "type": "number"
        },
        "nomeCliente": {
          "description": "Nome do Cliente",
          "type": "string",
          "minLength": 1
        },
        "quantidadeDeComprasDoCliente": {
          "description": "Quantidade de compras realizadas (fidelidade do cliente)",
          "type": "integer"
        },
        "totalEmComprasDoCliente": {
          "description": "Total em compras realizadas pelo cliente",
          "type": "number"
        }
      }
    },
    "Erro": {
      "type": "object",
      "properties": {
        "Mensagem": {
          "type": "string"
        }
      }
    },
    "Token": {
      "type": "string",
      "minLength": 1
    },
    "VinhoRecomendado": {
      "description": "Recomendação de vinho para um cliente determinado",
      "type": "object",
      "properties": {
        "categoria": {
          "description": "Categoria do Vinho",
          "type": "string",
          "minLength": 1
        },
        "pais": {
          "description": "País de origem do vinho",
          "type": "string",
          "minLength": 1
        },
        "preco": {
          "description": "Preço do Vinho",
          "type": "number"
        },
        "produto": {
          "description": "Nome do Produto",
          "type": "string",
          "minLength": 1
        },
        "safra": {
          "description": "Ano da Safra do Vinho",
          "type": "integer"
        },
        "variedade": {
          "description": "Variedade do Vinho",
          "type": "string",
          "minLength": 1
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
