// Code generated by go-swagger; DO NOT EDIT.

package vinho

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"std/github.com/jpodlasnisky/DesafioUBOTs/models"
)

// RecomendacaoVinhoOKCode is the HTTP code returned for type RecomendacaoVinhoOK
const RecomendacaoVinhoOKCode int = 200

/*RecomendacaoVinhoOK Vinho recomendado

swagger:response recomendacaoVinhoOK
*/
type RecomendacaoVinhoOK struct {

	/*
	  In: Body
	*/
	Payload *models.VinhoRecomendado `json:"body,omitempty"`
}

// NewRecomendacaoVinhoOK creates RecomendacaoVinhoOK with default headers values
func NewRecomendacaoVinhoOK() *RecomendacaoVinhoOK {

	return &RecomendacaoVinhoOK{}
}

// WithPayload adds the payload to the recomendacao vinho o k response
func (o *RecomendacaoVinhoOK) WithPayload(payload *models.VinhoRecomendado) *RecomendacaoVinhoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the recomendacao vinho o k response
func (o *RecomendacaoVinhoOK) SetPayload(payload *models.VinhoRecomendado) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RecomendacaoVinhoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RecomendacaoVinhoInternalServerErrorCode is the HTTP code returned for type RecomendacaoVinhoInternalServerError
const RecomendacaoVinhoInternalServerErrorCode int = 500

/*RecomendacaoVinhoInternalServerError Status 500

swagger:response recomendacaoVinhoInternalServerError
*/
type RecomendacaoVinhoInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Erro `json:"body,omitempty"`
}

// NewRecomendacaoVinhoInternalServerError creates RecomendacaoVinhoInternalServerError with default headers values
func NewRecomendacaoVinhoInternalServerError() *RecomendacaoVinhoInternalServerError {

	return &RecomendacaoVinhoInternalServerError{}
}

// WithPayload adds the payload to the recomendacao vinho internal server error response
func (o *RecomendacaoVinhoInternalServerError) WithPayload(payload *models.Erro) *RecomendacaoVinhoInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the recomendacao vinho internal server error response
func (o *RecomendacaoVinhoInternalServerError) SetPayload(payload *models.Erro) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RecomendacaoVinhoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
