// Code generated by go-swagger; DO NOT EDIT.

package cliente

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"std/github.com/jpodlasnisky/DesafioUBOTs/models"
)

// ClienteMaiorCompraUnicaOKCode is the HTTP code returned for type ClienteMaiorCompraUnicaOK
const ClienteMaiorCompraUnicaOKCode int = 200

/*ClienteMaiorCompraUnicaOK Cliente com maior compra única

swagger:response clienteMaiorCompraUnicaOK
*/
type ClienteMaiorCompraUnicaOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cliente `json:"body,omitempty"`
}

// NewClienteMaiorCompraUnicaOK creates ClienteMaiorCompraUnicaOK with default headers values
func NewClienteMaiorCompraUnicaOK() *ClienteMaiorCompraUnicaOK {

	return &ClienteMaiorCompraUnicaOK{}
}

// WithPayload adds the payload to the cliente maior compra unica o k response
func (o *ClienteMaiorCompraUnicaOK) WithPayload(payload *models.Cliente) *ClienteMaiorCompraUnicaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cliente maior compra unica o k response
func (o *ClienteMaiorCompraUnicaOK) SetPayload(payload *models.Cliente) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ClienteMaiorCompraUnicaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ClienteMaiorCompraUnicaInternalServerErrorCode is the HTTP code returned for type ClienteMaiorCompraUnicaInternalServerError
const ClienteMaiorCompraUnicaInternalServerErrorCode int = 500

/*ClienteMaiorCompraUnicaInternalServerError Status 500

swagger:response clienteMaiorCompraUnicaInternalServerError
*/
type ClienteMaiorCompraUnicaInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Erro `json:"body,omitempty"`
}

// NewClienteMaiorCompraUnicaInternalServerError creates ClienteMaiorCompraUnicaInternalServerError with default headers values
func NewClienteMaiorCompraUnicaInternalServerError() *ClienteMaiorCompraUnicaInternalServerError {

	return &ClienteMaiorCompraUnicaInternalServerError{}
}

// WithPayload adds the payload to the cliente maior compra unica internal server error response
func (o *ClienteMaiorCompraUnicaInternalServerError) WithPayload(payload *models.Erro) *ClienteMaiorCompraUnicaInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cliente maior compra unica internal server error response
func (o *ClienteMaiorCompraUnicaInternalServerError) SetPayload(payload *models.Erro) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ClienteMaiorCompraUnicaInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
