// Code generated by go-swagger; DO NOT EDIT.

package cliente

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewClientesMaisFieisParams creates a new ClientesMaisFieisParams object
// no default values defined in spec.
func NewClientesMaisFieisParams() ClientesMaisFieisParams {

	return ClientesMaisFieisParams{}
}

// ClientesMaisFieisParams contains all the bound params for the clientes mais fieis operation
// typically these are obtained from a http.Request
//
// swagger:parameters clientesMaisFieis
type ClientesMaisFieisParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	TamanhoLista int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewClientesMaisFieisParams() beforehand.
func (o *ClientesMaisFieisParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTamanhoLista, rhkTamanhoLista, _ := route.Params.GetOK("tamanhoLista")
	if err := o.bindTamanhoLista(rTamanhoLista, rhkTamanhoLista, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTamanhoLista binds and validates parameter TamanhoLista from path.
func (o *ClientesMaisFieisParams) bindTamanhoLista(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("tamanhoLista", "path", "int64", raw)
	}
	o.TamanhoLista = value

	return nil
}
