// Code generated by go-swagger; DO NOT EDIT.

package cliente

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"std/github.com/jpodlasnisky/DesafioUBOTs/models"
)

// ClientesGastoTotalOKCode is the HTTP code returned for type ClientesGastoTotalOK
const ClientesGastoTotalOKCode int = 200

/*ClientesGastoTotalOK Clientes ordenados pelo total de compras

swagger:response clientesGastoTotalOK
*/
type ClientesGastoTotalOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Cliente `json:"body,omitempty"`
}

// NewClientesGastoTotalOK creates ClientesGastoTotalOK with default headers values
func NewClientesGastoTotalOK() *ClientesGastoTotalOK {

	return &ClientesGastoTotalOK{}
}

// WithPayload adds the payload to the clientes gasto total o k response
func (o *ClientesGastoTotalOK) WithPayload(payload []*models.Cliente) *ClientesGastoTotalOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the clientes gasto total o k response
func (o *ClientesGastoTotalOK) SetPayload(payload []*models.Cliente) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ClientesGastoTotalOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Cliente, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ClientesGastoTotalInternalServerErrorCode is the HTTP code returned for type ClientesGastoTotalInternalServerError
const ClientesGastoTotalInternalServerErrorCode int = 500

/*ClientesGastoTotalInternalServerError Status 500

swagger:response clientesGastoTotalInternalServerError
*/
type ClientesGastoTotalInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Erro `json:"body,omitempty"`
}

// NewClientesGastoTotalInternalServerError creates ClientesGastoTotalInternalServerError with default headers values
func NewClientesGastoTotalInternalServerError() *ClientesGastoTotalInternalServerError {

	return &ClientesGastoTotalInternalServerError{}
}

// WithPayload adds the payload to the clientes gasto total internal server error response
func (o *ClientesGastoTotalInternalServerError) WithPayload(payload *models.Erro) *ClientesGastoTotalInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the clientes gasto total internal server error response
func (o *ClientesGastoTotalInternalServerError) SetPayload(payload *models.Erro) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ClientesGastoTotalInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
